version: '3.1'

services:

  mongo:
    image: mongo
    command: [ --auth ]
    ports:
      - 27017:27017
    volumes: 
      - pew_mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: passwd

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: passwd

volumes:
  pew_mongodb: